import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats

def plot_energy_data(csv_file):
    try:
        # Read the CSV generated by pyJoules
        df = pd.read_csv(csv_file, sep=';')
        
        # Convert microjoules to Joules for the CPU package
        package_joules = df['package_0'] / 1_000_000
        mean_val = package_joules.mean()
        std_val = package_joules.std()
        
        # Enable a clean, minimalist style
        plt.style.use('seaborn-v0_8-whitegrid')
        
        # Academic color palette
        primary_color = '#1f77b4' 
        mean_color = '#d62728'    
        
        # Create figure: make the line graph wider than the histogram
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4), gridspec_kw={'width_ratios': [2, 1.2]})
        fig.patch.set_facecolor('white')
        
        # --- Plot 1: Line graph (Zoomed In) ---
        ax1.plot(range(1, len(package_joules) + 1), package_joules, 
                 marker='o', markersize=5, linestyle='-', linewidth=1.5, color=primary_color)
        
        # Add a horizontal line for the Mean
        ax1.axhline(mean_val, color=mean_color, linestyle='--', linewidth=1.5, 
                    label=f'Mean: {mean_val:.1f} J')
        
        # Zoom the Y-axis in so variance is visible but stability is clear
        ax1.set_ylim(mean_val - (std_val * 4), mean_val + (std_val * 4))
        
        ax1.set_title('CPU Package Energy (Baseline Stability)', fontsize=12, fontweight='bold', pad=10)
        ax1.set_xlabel('Benchmark Iteration (30 Runs)', fontsize=11)
        ax1.set_ylabel('Energy Consumed (Joules)', fontsize=11)
        ax1.legend(loc='upper right', frameon=True)
        
        # Clean up borders
        for spine in ['top', 'right']:
            ax1.spines[spine].set_visible(False)
            
        # --- Plot 2: Histogram & Bell Curve ---
        count, bins, ignored = ax2.hist(package_joules, bins=8, density=True, 
                                        alpha=0.6, color=primary_color, edgecolor='black')
        
        # Overlay the normal distribution curve
        x = np.linspace(mean_val - 3*std_val, mean_val + 3*std_val, 100)
        ax2.plot(x, stats.norm.pdf(x, mean_val, std_val), color=mean_color, linewidth=2)
        
        ax2.set_title('Statistical Distribution', fontsize=12, fontweight='bold', pad=10)
        ax2.set_xlabel('Joules', fontsize=11)
        ax2.set_yticks([]) # Hide Y ticks as density numbers aren't needed for the story
        
        # Clean up borders
        for spine in ['top', 'right', 'left']:
            ax2.spines[spine].set_visible(False)
        
        # Save as a vector PDF for crisp LaTeX rendering
        plt.tight_layout()
        plt.savefig('energy_baseline_plot.pdf', format='pdf', bbox_inches='tight')
        print("Success: Generated 'energy_baseline_plot.pdf'")
        
    except FileNotFoundError:
        print(f"Error: {csv_file} not found. Run the benchmark loop first!")
    except Exception as e:
        print(f"An error occurred: {e}. (Make sure 'scipy' is installed: pip install scipy)")

if __name__ == "__main__":
    plot_energy_data('baseline_energy.csv')